apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: workload-java-native-traffic-split
  namespace: business-development
  labels:
    apps.tanzu.vmware.com/workload-type: web-traffic-split
    app.kubernetes.io/part-of: workload-java-native
spec:
  build:
    env:
      - name: BP_NATIVE_IMAGE
        value: "true"
  source:
    git:
      url: https://github.com/showpune/java-native.git
      ref:
        branch: master
