apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  annotations:
    kapp.k14s.io/identity: v1;/carto.run/ClusterSupplyChain/source-to-url;carto.run/v1alpha1
    kapp.k14s.io/original: '{"apiVersion":"carto.run/v1alpha1","kind":"ClusterSupplyChain","metadata":{"labels":{"kapp.k14s.io/app":"1647776999207417527","kapp.k14s.io/association":"v1.4e1a1027543b1d663294132ebfdd4f33"},"name":"source-to-url"},"spec":{"params":[{"default":"main","name":"gitops_branch"},{"default":"supplychain","name":"gitops_user_name"},{"default":"supplychain","name":"gitops_user_email"},{"default":"supplychain@cluster.local","name":"gitops_commit_message"},{"default":"","name":"gitops_ssh_secret"}],"resources":[{"name":"source-provider","params":[{"name":"serviceAccount","value":"default"}],"templateRef":{"kind":"ClusterSourceTemplate","name":"source-template"}},{"name":"deliverable","params":[{"name":"registry","value":{"repository":"showpune","server":"index.docker.io"}}],"templateRef":{"kind":"ClusterTemplate","name":"deliverable-template"}},{"name":"image-builder","params":[{"name":"serviceAccount","value":"default"},{"name":"clusterBuilder","value":"default"},{"name":"registry","value":{"repository":"showpune","server":"index.docker.io"}}],"sources":[{"name":"source","resource":"source-provider"}],"templateRef":{"kind":"ClusterImageTemplate","name":"kpack-template"}},{"images":[{"name":"image","resource":"image-builder"}],"name":"config-provider","params":[{"name":"serviceAccount","value":"default"}],"templateRef":{"kind":"ClusterConfigTemplate","name":"convention-template"}},{"configs":[{"name":"config","resource":"config-provider"}],"name":"app-config","templateRef":{"kind":"ClusterConfigTemplate","name":"config-template"}},{"configs":[{"name":"config","resource":"app-config"}],"name":"config-writer","params":[{"name":"serviceAccount","value":"default"},{"name":"registry","value":{"repository":"showpune","server":"index.docker.io"}}],"templateRef":{"kind":"ClusterTemplate","name":"config-writer-template"}}],"selector":{"apps.tanzu.vmware.com/workload-type":"web"}}}'
    kapp.k14s.io/original-diff-md5: c6e94dc94aed3401b5d0f26ed6c0bff3
  creationTimestamp: "2022-03-20T11:49:59Z"
  generation: 1
  labels:
    kapp.k14s.io/app: "1647776999207417527"
    kapp.k14s.io/association: v1.4e1a1027543b1d663294132ebfdd4f33
  name: source-to-url
  resourceVersion: "11398"
  uid: f52a1316-f6c7-4016-817d-63f46c250522
spec:
  params:
    - default: main
      name: gitops_branch
    - default: supplychain
      name: gitops_user_name
    - default: supplychain
      name: gitops_user_email
    - default: supplychain@cluster.local
      name: gitops_commit_message
    - default: ""
      name: gitops_ssh_secret
  resources:
    - name: source-provider
      params:
        - name: serviceAccount
          value: default
      templateRef:
        kind: ClusterSourceTemplate
        name: source-template
    - name: deliverable
      params:
        - name: registry
          value:
            repository: showpune
            server: index.docker.io
      templateRef:
        kind: ClusterTemplate
        name: deliverable-template
    - name: image-builder
      params:
        - name: serviceAccount
          value: default
        - name: clusterBuilder
          value: default
        - name: registry
          value:
            repository: showpune
            server: index.docker.io
      sources:
        - name: source
          resource: source-provider
      templateRef:
        kind: ClusterImageTemplate
        name: kpack-template
    - name: config-provider
      images:
        - name: image
          resource: image-builder
      params:
        - name: serviceAccount
          value: default
      templateRef:
        kind: ClusterConfigTemplate
        name: convention-template
    - name: app-config
      configs:
        - name: config
          resource: config-provider
      templateRef:
        kind: ClusterConfigTemplate
        name: config-template
    - name: config-writer
      configs:
        - name: config
          resource: app-config
      params:
        - name: serviceAccount
          value: default
        - name: registry
          value:
            repository: showpune
            server: index.docker.io
      templateRef:
        kind: ClusterTemplate
        name: config-writer-template
  selector:
    apps.tanzu.vmware.com/workload-type: web
status:
  conditions:
    - lastTransitionTime: "2022-03-20T11:50:00Z"
      message: ""
      reason: Ready
      status: "True"
      type: TemplatesReady
    - lastTransitionTime: "2022-03-20T11:50:00Z"
      message: ""
      reason: Ready
      status: "True"
      type: Ready
  observedGeneration: 1
